#! /bin/bash --login
# Time job will take to execute (HH:MM:SS format) 
#PBS -l walltime=24:00:00 
# Memory needed by the job 
#PBS -l mem=250Gb 
# Number of shared memory nodes required and the number of processors per node
#PBS -l nodes=1:ppn=4
# Make output and error files the same file 
#PBS -j oe
# Send an email when a job is aborted, begins or ends 
#PBS -m abe
# Give the job a name
#PBS -N centralia_megahit_total
#_______________________________________________________________________# 

cd ~/Centralia

module load megahit

megahit --cpu-only -m 60e9 -l 250 -r total_normed.fastq -o total_megahit

#end 
#_______________________________________________________________________# 
# PBS stats 
cat ${PBS_NODEFILE} 
env | grep PBS 
qstat -f ${PBS_JOBID} 




