#! /bin/bash --login
# Time job will take to execute (HH:MM:SS format) 
#PBS -l walltime=04:00:00 
# Memory needed by the job 
#PBS -l mem=50Gb 
# Number of shared memory nodes required and the number of processors per node
#PBS -l nodes=1:ppn=4
# Make output and error files the same file 
#PBS -j oe
# Send an email when a job is aborted, begins or ends 
#PBS -m abe
# Give the job a name
#PBS -N pool_1 
#_______________________________________________________________________# 

cd ~/Centralia

module load khmer/1.2

module load FASTX/0.0.14

fastq_quality_filter -Q33 -q 30 -p 50  -i pooled.fastq -o pooled_trim.fastq

qsub pool_2_03262015.qsub

#end 
#_______________________________________________________________________# 
# PBS stats 
cat ${PBS_NODEFILE} 
env | grep PBS 
qstat -f ${PBS_JOBID} 




